# Generated by Django 5.0.4 on 2024-05-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='de',
            old_name='no',
            new_name='age',
        ),
    ]
