# Generated by Django 5.0.4 on 2024-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broapp', '0002_rename_no_de_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='de',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
